# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello World"
          command: "echo Hello, World!"

  install-module:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: "Change directory to TYPESCRIPT"
          command: "cd ./TYPESCRIPT"
      - run:
          name: "Install dependencies"
          command: "npm install"

  run-test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: "Change directory to TYPESCRIPT"
          command: "cd ./TYPESCRIPT"
      - run:
          name: "running test"
          command: "npm run test"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - install-module
      - run-test